(() => {
'use strict';
const $=id=>document.getElementById(id), cfg=window.OSTL_SUPABASE;
if(!cfg?.url || !cfg?.anonKey || cfg.url.includes('PASTE_')) throw Error('Open supabase-config.js and add your Supabase URL and publishable/anon key.');
const sb=window.supabase.createClient(cfg.url,cfg.anonKey,{auth:{persistSession:true,autoRefreshToken:true}});
const params=new URLSearchParams(location.search), DOMAIN='ozarktravelstein.app';
let S={user:null,role:'spectator',group:1,tid:null,t:null,players:[],scores:[],channel:null,hole:1};
const show=id=>['login','home','create','event'].forEach(x=>$(x).classList.toggle('hidden',x!==id));
const toast=m=>{$('toast').textContent=m;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2800)};
const status=(m,e=false)=>{$('status').textContent=m;$('status').classList.toggle('error',e)};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const usernameEmail=v=>{const u=String(v||'').trim().toLowerCase();if(!/^[a-z0-9._-]{3,30}$/.test(u))throw Error('Username must be 3–30 letters, numbers, dots, dashes, or underscores.');return `${u}@${DOMAIN}`};
const randomToken=()=>Array.from(crypto.getRandomValues(new Uint8Array(24)),b=>b.toString(16).padStart(2,'0')).join('');
const check=({error})=>{if(error)throw error};
function groups(el){el.innerHTML=Array.from({length:6},(_,i)=>`<option value="${i+1}">Group ${i+1}</option>`).join('')}; groups($('playerGroup'));groups($('groupSelect'));
async function anonymous(){let {data}=await sb.auth.getSession();if(data.session)return data.session.user;const r=await sb.auth.signInAnonymously();check(r);return r.data.user}
async function boot(){try{if(params.get('t')&&params.get('g')&&params.get('token')){await anonymous();const r=await sb.rpc('claim_group_link',{p_tournament:params.get('t'),p_group:Number(params.get('g')),p_token:params.get('token')});check(r);S.role='group';S.group=Number(params.get('g'));await openEvent(params.get('t'));return}if(params.get('spectator')){await anonymous();const r=await sb.from('tournaments').select('id').eq('is_active',true).order('created_at',{ascending:false}).limit(1).maybeSingle();check(r);if(!r.data)throw Error('No active tournament is selected.');S.role='spectator';await openEvent(r.data.id);return}const {data}=await sb.auth.getSession();if(data.session?.user && !data.session.user.is_anonymous){S.user=data.session.user;S.role='admin';await loadHome()}else{show('login');status('Administrator sign-in required.')}}catch(e){status(e.message,true);show('login')}}
$('loginBtn').onclick=async()=>{try{const r=await sb.auth.signInWithPassword({email:usernameEmail($('username').value),password:$('password').value});check(r);S.user=r.data.user;S.role='admin';await loadHome()}catch(e){status(e.message,true)}};
$('logoutBtn').onclick=async()=>{await sb.auth.signOut();location.href=location.pathname}; $('spectatorBtn').onclick=()=>location.href='?spectator=1';
$('newBtn').onclick=()=>show('create');document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show('home'));$('backBtn').onclick=()=>{unsubscribe();loadHome()};
async function loadHome(){show('home');status('Connected as administrator.');const r=await sb.from('tournaments').select('*').order('date',{ascending:false});check(r);$('tournaments').innerHTML=!r.data.length?'<p>No tournaments yet.</p>':r.data.map(t=>`<button class="secondary full eventBtn" data-id="${t.id}">${esc(t.name)} — ${esc(t.course||'')}</button>`).join('');document.querySelectorAll('.eventBtn').forEach(b=>b.onclick=()=>openEvent(b.dataset.id))}
$('createBtn').onclick=async()=>{try{const holes=Number($('newHoles').value),pars=Array.from({length:holes},(_,i)=>[4,4,3,5,4,4,3,5,4][i%9]),stroke=Array.from({length:holes},(_,i)=>i+1);const u=(await sb.auth.getUser()).data.user;if(!u)throw Error('Your admin session expired. Sign in again.');const r=await sb.from('tournaments').insert({admin_user_id:u.id,name:$('newName').value.trim(),course:$('newCourse').value.trim(),date:$('newDate').value,holes,pars,stroke_indexes:stroke}).select().single();check(r);await openEvent(r.data.id)}catch(e){status(e.message,true)}};
function unsubscribe(){if(S.channel){sb.removeChannel(S.channel);S.channel=null}}
async function openEvent(id){S.tid=id;show('event');unsubscribe();await reloadEvent();S.channel=sb.channel(`event:${id}`).on('postgres_changes',{event:'*',schema:'public',table:'scores',filter:`tournament_id=eq.${id}`},reloadScores).on('postgres_changes',{event:'*',schema:'public',table:'players',filter:`tournament_id=eq.${id}`},reloadPlayers).on('postgres_changes',{event:'UPDATE',schema:'public',table:'tournaments',filter:`id=eq.${id}`},reloadTournament).subscribe();status(`Connected • ${S.role}`)}
async function reloadEvent(){await Promise.all([reloadTournament(),reloadPlayers(),reloadScores()])}
async function reloadTournament(){const r=await sb.from('tournaments').select('*').eq('id',S.tid).single();check(r);S.t=r.data;renderAll()}
async function reloadPlayers(){const r=await sb.from('players').select('*').eq('tournament_id',S.tid).order('name');check(r);S.players=r.data||[];renderAll()}
async function reloadScores(){const r=await sb.from('scores').select('*').eq('tournament_id',S.tid);check(r);S.scores=r.data||[];renderAll()}
const admin=()=>S.role==='admin';
function renderAll(){if(!S.t)return;$('eventName').textContent=S.t.name;$('eventMeta').textContent=`${S.t.course||''} • ${S.t.date||''} • ${S.t.holes} holes`;$('roleBadge').textContent=admin()?'ADMIN':S.role==='group'?`GROUP ${S.group}`:'SPECTATOR';applyRoleUI();renderLeader();renderScores();renderPlayers();renderSetup();renderSkins()}
function applyRoleUI(){document.querySelectorAll('[data-tab]').forEach(b=>{const id=b.dataset.tab;b.classList.toggle('hidden',S.role==='spectator'&&!['leader','skins'].includes(id));});if(S.role==='spectator'){const active=document.querySelector('[data-tab].active');if(active&&!['leader','skins'].includes(active.dataset.tab))document.querySelector('[data-tab="leader"]').click();}}
document.querySelectorAll('[data-tab]').forEach((b,i)=>{if(i===0)b.classList.add('active');b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.pane').forEach(x=>x.classList.add('hidden'));const id=b.dataset.tab;if(S.role==='spectator'&&!['leader','skins'].includes(id)){document.querySelector('[data-tab="leader"]').click();return}if((id==='players'||id==='setup')&&!admin()){toast('Administrator only');document.querySelector('[data-tab="leader"]').click();return}$(id).classList.remove('hidden');renderAll()}});
function strokesOnHole(handicap,hole){const hc=Number(handicap||0), holes=S.t.holes, si=Number(S.t.stroke_indexes?.[hole-1]||hole);if(hc===0)return 0;const sign=hc<0?-1:1, abs=Math.abs(hc), base=Math.floor(abs/holes), rem=abs%holes;return sign*(base+(si<=rem?1:0))}
function net(p,h,gross){return gross-strokesOnHole(p.course_handicap,h)}
function renderLeader(){const rows=S.players.map(p=>{const ss=S.scores.filter(s=>s.player_id===p.id).sort((a,b)=>a.hole-b.hole),gross=ss.reduce((a,s)=>a+Number(s.gross||0),0),netTotal=ss.reduce((a,s)=>a+net(p,s.hole,s.gross),0),par=ss.reduce((a,s)=>a+Number(S.t.pars?.[s.hole-1]||4),0),thru=ss.length,val=thru?netTotal-par:0;return{p,thru,gross,netTotal,val}}).sort((a,b)=>{if(a.thru===0&&b.thru>0)return 1;if(b.thru===0&&a.thru>0)return-1;return a.val-b.val||b.thru-a.thru||a.netTotal-b.netTotal||a.p.name.localeCompare(b.p.name)});let lastVal=null,lastThru=null,rank=0;$('leader').innerHTML='<div class="leaderTitleRow"><div><h2>Leaderboard</h2><p class="muted">Net standings • Gross / Net / Course Handicap</p></div><div class="leaderCols"><span>THRU</span><span>TO PAR</span></div></div>'+(!rows.length?'<p>No players yet.</p>':rows.map((r,i)=>{if(r.thru===0){rank=i+1}else if(r.val!==lastVal||r.thru!==lastThru){rank=i+1}lastVal=r.val;lastThru=r.thru;const toPar=r.thru===0?'—':r.val===0?'E':r.val>0?`+${r.val}`:String(r.val);return`<div class="leaderRow"><b class="leaderRank">${rank}</b><div class="leaderPlayer"><strong>${esc(r.p.name)}</strong><span>Gross ${r.thru?r.gross:'—'} · Net ${r.thru?r.netTotal:'—'} · CH ${Number(r.p.course_handicap||0)}</span></div><b class="leaderThru">${r.thru||'—'}</b><b class="leaderToPar ${r.val<0?'under':r.val>0?'over':''}">${toPar}</b></div>`}).join(''))}
function renderScores(){if(!S.t)return;const allowed=S.role==='group'?[S.group]:[1,2,3,4,5,6];if(!allowed.includes(Number(S.group)))S.group=allowed[0];$('groupSelect').innerHTML=allowed.map(g=>`<option value="${g}" ${Number(g)===Number(S.group)?'selected':''}>Group ${g}</option>`).join('');$('groupSelect').disabled=S.role==='group'||S.role==='spectator';$('holeSelect').innerHTML=Array.from({length:S.t.holes},(_,i)=>`<option value="${i+1}" ${i+1===S.hole?'selected':''}>Hole ${i+1}</option>`).join('');const g=Number(S.group),h=Number(S.hole);const par=S.t.pars?.[h-1]||4,si=S.t.stroke_indexes?.[h-1]||h;const meta=$('scoreHoleMeta'); if(meta) meta.innerHTML=`<b>Hole ${h}</b> • Par ${par} • Handicap ${si}`;const ps=S.players.filter(p=>p.group_number===g);if(S.role==='spectator'){$('scoreGrid').innerHTML='<p>Spectator mode is view-only. Use the Leaderboard or Skins tabs.</p>';return}$('scoreGrid').innerHTML=ps.length?ps.map(p=>{const old=S.scores.find(s=>s.player_id===p.id&&s.hole===h);const netText=old?`Gross ${old.gross} • Net ${net(p,h,old.gross)}`:'Tap score';return`<div class="scoreplayer"><div class="scorePlayerHead"><b>${esc(p.name)}</b><span>HCP ${p.course_handicap||0} • ${netText}</span></div><div class="numbers">${Array.from({length:12},(_,i)=>`<button type="button" data-p="${p.id}" data-g="${g}" data-v="${i+1}" class="${old?.gross===i+1?'selected':''}">${i+1}</button>`).join('')}</div></div>`}).join(''):'<p>No players are assigned to this group yet. Add players in the Players tab.</p>';document.querySelectorAll('.numbers button').forEach(b=>b.onclick=()=>saveScore(b.dataset.p,Number(b.dataset.g),h,Number(b.dataset.v)))}
$('groupSelect').onchange=()=>{S.group=Number($('groupSelect').value);renderScores()};$('holeSelect').onchange=()=>{S.hole=Number($('holeSelect').value);renderScores()};$('prevHole').onclick=()=>{S.hole=Math.max(1,S.hole-1);renderScores()};$('nextHole').onclick=()=>{S.hole=Math.min(S.t.holes,S.hole+1);renderScores()};
async function saveScore(pid,g,h,v){try{const u=(await sb.auth.getUser()).data.user;if(!u)throw Error('Session expired. Reopen your scoring link.');const r=await sb.from('scores').upsert({tournament_id:S.tid,player_id:pid,group_number:g,hole:h,gross:v,updated_by:u.id},{onConflict:'player_id,hole'}).select();check(r);await reloadScores();toast(`${S.players.find(x=>x.id===pid)?.name}: ${v}`)}catch(e){status(e.message,true);toast(e.message)}}
function renderPlayers(){if(!admin())return;$('playerList').innerHTML=S.players.length?S.players.map(p=>`<div class="player editPlayer"><div class="playerIdentity"><b>${esc(p.name)}</b><small>Current: Group ${p.group_number} • CH ${Number(p.course_handicap||0)}</small></div><label>Course handicap<input class="editPlayerHcp" data-id="${p.id}" type="number" value="${Number(p.course_handicap||0)}"></label><label>Group<select class="editPlayerGroup" data-id="${p.id}">${Array.from({length:6},(_,i)=>`<option value="${i+1}" ${i+1===Number(p.group_number)?'selected':''}>Group ${i+1}</option>`).join('')}</select></label><div class="playerActions"><button type="button" class="secondary savePlayerChanges" data-id="${p.id}">Save Changes</button><button type="button" class="danger deletePlayer" data-id="${p.id}" data-name="${esc(p.name)}">Delete Player</button></div></div>`).join(''):'<p>No players added yet.</p>';document.querySelectorAll('.savePlayerChanges').forEach(b=>b.onclick=()=>savePlayerChanges(b.dataset.id));document.querySelectorAll('.deletePlayer').forEach(b=>b.onclick=()=>deletePlayer(b.dataset.id,b.dataset.name))}
async function savePlayerChanges(id){try{const hcp=Number(document.querySelector(`.editPlayerHcp[data-id="${id}"]`).value),group=Number(document.querySelector(`.editPlayerGroup[data-id="${id}"]`).value);if(!Number.isFinite(hcp)||hcp<-20||hcp>60)throw Error('Enter a handicap between -20 and 60.');if(group<1||group>6)throw Error('Choose Group 1 through 6.');const r=await sb.from('players').update({course_handicap:hcp,group_number:group}).eq('id',id).eq('tournament_id',S.tid).select().single();check(r);const sr=await sb.from('scores').update({group_number:group}).eq('player_id',id).eq('tournament_id',S.tid);check(sr);await Promise.all([reloadPlayers(),reloadScores()]);toast(`${r.data.name} updated • Group ${group} • CH ${hcp}`)}catch(e){status(e.message,true);toast(e.message)}}
async function deletePlayer(id,name){if(!confirm(`Delete ${name}? This will also permanently delete all of this player's scores from this tournament.`))return;try{const r=await sb.from('players').delete().eq('id',id).eq('tournament_id',S.tid);check(r);await Promise.all([reloadPlayers(),reloadScores()]);toast(`${name} deleted`)}catch(e){status(e.message,true);toast(e.message)}}
$('addPlayer').onclick=async()=>{try{const name=$('playerName').value.trim();if(!name)throw Error('Enter a player name.');const payload={tournament_id:S.tid,name,course_handicap:Number($('playerHcp').value||0),group_number:Number($('playerGroup').value)};const r=await sb.from('players').insert(payload).select().single();check(r);$('playerName').value='';await reloadPlayers();S.group=r.data.group_number;renderScores();toast(`${r.data.name} added to Group ${r.data.group_number}`)}catch(e){status(e.message,true);toast(e.message)}};
function renderSetup(){if(!admin()||!S.t)return;$('editName').value=S.t.name||'';$('editCourse').value=S.t.course||'';$('editDate').value=S.t.date||'';$('activeEvent').checked=!!S.t.is_active;$('holeSetup').innerHTML=`<div class="holeSetupHeader"><b>Hole</b><b>Par</b><b>Handicap</b><b>HCP Skin</b><b>Blind Skin</b></div>`+Array.from({length:S.t.holes},(_,i)=>{const h=i+1;return`<div class="holeRow"><b>${h}</b><input class="holePar" data-hole="${h}" type="number" min="3" max="6" value="${S.t.pars?.[i]||4}"><input class="holeSI" data-hole="${h}" type="number" min="1" max="${S.t.holes}" value="${S.t.stroke_indexes?.[i]||h}"><label class="checkLabel"><input type="checkbox" class="hcpSkin" value="${h}" ${S.t.handicap_skin_holes?.includes(h)?'checked':''}></label><label class="checkLabel"><input type="checkbox" class="blindSkin" value="${h}" ${S.t.blind_skin_holes?.includes(h)?'checked':''}></label></div>`}).join('')}
$('saveSetup').onclick=async()=>{try{const active=$('activeEvent').checked,pars=[...document.querySelectorAll('.holePar')].map(x=>Number(x.value)),stroke=[...document.querySelectorAll('.holeSI')].map(x=>Number(x.value));if(pars.some(x=>x<3||x>6))throw Error('Pars must be between 3 and 6.');if(stroke.some(x=>x<1||x>S.t.holes)||new Set(stroke).size!==S.t.holes)throw Error(`Hole handicaps must use each number 1–${S.t.holes} exactly once.`);if(active){const q=await sb.from('tournaments').update({is_active:false}).neq('id',S.tid);check(q)}const r=await sb.from('tournaments').update({name:$('editName').value,course:$('editCourse').value,date:$('editDate').value,is_active:active,pars,stroke_indexes:stroke,handicap_skin_holes:[...document.querySelectorAll('.hcpSkin:checked')].map(x=>Number(x.value)),blind_skin_holes:[...document.querySelectorAll('.blindSkin:checked')].map(x=>Number(x.value))}).eq('id',S.tid).select().single();check(r);S.t=r.data;renderAll();toast('Tournament setup saved')}catch(e){status(e.message,true);toast(e.message)}};
$('generateLinks').onclick=async()=>{try{const links={};for(let g=1;g<=6;g++){const tok=randomToken();links[g]=tok;check(await sb.from('group_links').upsert({tournament_id:S.tid,group_number:g,token:tok},{onConflict:'tournament_id,group_number'}))}renderLinks(links)}catch(e){status(e.message,true);toast(e.message)}};
function renderLinks(tokens){if(!tokens){$('links').innerHTML='<p>Generate links to display a new set.</p>';return}const base=location.origin+location.pathname;$('links').innerHTML=Object.entries(tokens).map(([g,t])=>{const u=`${base}?t=${S.tid}&g=${g}&token=${t}`;return`<div class="linkrow"><b>Group ${g}</b><br><input readonly value="${u}"><button data-copy="${u}">Copy</button></div>`}).join('')+`<div class="linkrow"><b>Spectator</b><br><input readonly value="${base}?spectator=1"><button data-copy="${base}?spectator=1">Copy</button></div>`;document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copy);toast('Copied')})}
$('clearScores').onclick=async()=>{if(!confirm('Clear every score while keeping the tournament, course and players?'))return;try{const r=await sb.from('scores').delete().eq('tournament_id',S.tid);check(r);await reloadScores();toast('Scores cleared')}catch(e){status(e.message,true);toast(e.message)}};
function skinResults(holes,isNet){
  if(!holes?.length)return '<p>No holes selected.</p>';
  const total=S.players.length;
  return holes.map(h=>{
    if(total===0)return `<div class="skinrow skinWaiting"><div class="skinHole">Hole ${h}</div><div class="skinStatus">No players in tournament yet</div></div>`;
    const entries=S.players.map(p=>{
      const score=S.scores.find(x=>x.player_id===p.id&&x.hole===h);
      return score?{p,v:isNet?net(p,h,score.gross):Number(score.gross)}:null;
    }).filter(Boolean);
    const posted=entries.length;
    const label=isNet?'Net':'Gross';
    if(!posted)return `<div class="skinrow skinWaiting"><div class="skinTop"><b>Hole ${h}</b><span class="skinProgress">0/${total} posted</span></div><div class="skinStatus">Waiting for first score</div></div>`;
    const low=Math.min(...entries.map(x=>x.v));
    const leaders=entries.filter(x=>x.v===low);
    const names=leaders.map(x=>esc(x.p.name)).join(', ');
    const final=posted===total;
    const tied=leaders.length>1;
    return `<div class="skinrow ${final?'skinFinal':'skinLive'}"><div class="skinTop"><b>Hole ${h}</b><span class="skinProgress">${posted}/${total} posted</span></div><div class="skinStatus"><span class="skinBadge">${final?'FINAL':'LIVE'}</span> <strong>${final?(tied?'Winners':'Winner'):(tied?'Current leaders':'Current leader')}:</strong> ${names}</div><div class="skinScore">${label} ${low}</div></div>`;
  }).join('');
}
function renderSkins(){if(!S.t)return;$('handicapSkins').innerHTML=skinResults(S.t.handicap_skin_holes,true);$('blindSkins').innerHTML=skinResults(S.t.blind_skin_holes,false);if(admin())renderLinks()}
window.addEventListener('error',e=>status(e.message,true));boot();
})();
